Create function Post
nhulongctk35/framgia-react-base pull request #1
Opened 2017-10-03 13:55 UTC by mackeno19932011

2017-10-06 15:10 UTC, nhulongctk10 commented on src/actions/PostAction.jsx
> +    adapter: null,
`params vs adapter` default value la null roi nen ko can truyen vao.

2017-10-06 15:16 UTC, nhulongctk10 requested changes

2017-10-06 15:16 UTC, nhulongctk10 commented on src/actions/PostAction.jsx
> +    .then(response => dispatch(fetchPostData(response.data)))
Ở đây nên xử dụng async / await

2017-10-06 15:16 UTC, nhulongctk10 commented on src/components/pages/Posts/PostList.jsx
> +  const rows = props.posts.map(post =>
`row -> postRow`

2017-10-06 15:16 UTC, nhulongctk10 commented on src/components/pages/Posts/PostList.jsx
> +const PostList = (props) => {
`(props) => ({ posts })`

2017-10-06 15:16 UTC, nhulongctk10 commented on src/components/pages/Posts/PostList.jsx
> +import PostRow from './PostRow';
cần 1 empty line giữa import thư viện với import files trong source.

2017-10-06 15:16 UTC, nhulongctk10 commented on src/components/pages/Posts/PostList.jsx
> +      { rows }
ko cần có space trong { }

2017-10-06 15:16 UTC, nhulongctk10 commented on src/components/pages/Posts/index.jsx
> +
xóa empty line.

2017-10-06 15:16 UTC, nhulongctk10 commented on src/components/pages/Posts/index.jsx
> +  {
format code:

2017-10-09 14:11 UTC, nhulongctk35 commented on src/actions/PostAction.jsx
> +function fetchPostData(data) {
Hàm này ko phải là fetchPost mà là receivePosts or fetchPostSuccess.

2017-10-09 14:11 UTC, nhulongctk35 commented on src/actions/PostAction.jsx
> +function fetchPostData(data) {
data ở đây nên spcecify là posts or postList

2017-10-09 14:12 UTC, nhulongctk35 commented on src/actions/PostAction.jsx
> +    posts: data,
ở đây chỉ cần viết lại là
```
{
  type: 'FETCH_POSTS_SUCCESS',
  posts,
}
```

2017-10-09 14:13 UTC, nhulongctk35 commented on src/actions/PostAction.jsx
> +    posts: data,
action type nên diễn tả đúng là action này làm gì.

2017-10-09 14:14 UTC, nhulongctk35 commented on src/actions/PostAction.jsx
> +const getPostData = async (dispatch) => {
thường những gì mà mình call api thì viết theo prefix là fetchSomething. Ở đây là mình fetch list posts nên sẽ là `fetchPosts`

2017-10-09 14:14 UTC, nhulongctk35 commented on src/actions/PostAction.jsx
> +  const postPromise = await UnauthenticatedRequest().get({
ở đây sao lại postPromise, hàm này trả về posts thì nên khai báo là const posts = ...

2017-10-10 13:24 UTC, nhulongctk35 approved these changes
LGTM 👍

2017-10-10 13:24 UTC, merged